[package]
name = "link_checker"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "rustls-tls"] }
lazy_static = "1"

config = { path = "../config" }
errors = { path = "../errors" }

[dev-dependencies]
mockito = "0.23"
