[package]
name = "front_matter"
version = "0.1.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]

[dependencies]
tera = "0.10"
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
regex = "0.2"
lazy_static = "0.2"


errors = { path = "../errors" }
