[package]
name = "front_matter"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
tera = "0.11"
chrono = "0.4"
serde = "1"
serde_derive = "1"
toml = "0.4"
regex = "0.2"
lazy_static = "1"


errors = { path = "../errors" }
