[package]
name = "rendering"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
tera = "0.11"
regex = "0.2"
lazy_static = "1"
syntect = "2"
pulldown-cmark = "0"
slug = "0.1"
serde = "1"
serde_derive = "1"

errors = { path = "../errors" }
front_matter = { path = "../front_matter" }
highlighting = { path = "../highlighting"}
utils = { path = "../utils" }

[dev-dependencies]
templates = { path = "../templates" }
