[package]
name = "render"
edition.workspace = true
version.workspace = true

[dependencies]
ahash = { workspace = true }
tera = {workspace = true, features = ["fast"]}


config = { workspace = true }
content = { workspace = true }
errors = { workspace = true }
