[package]
name = "utils"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
errors = { path = "../errors" }
tera = "1"
unicode-segmentation = "1.2"
walkdir = "2"
toml = "0.5"
serde = "1"
slug = "0.1"

[dev-dependencies]
tempfile = "3"
