[package]
name = "utils"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"
include = ["src/**/*"]

[dependencies]
tera = "1"
unicode-segmentation = "1.2"
walkdir = "2"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
slug = "0.1"
percent-encoding = "2"
filetime = "0.2.12"
minify-html = "0.4.2"

errors = { path = "../errors" }

[dev-dependencies]
tempfile = "3"
