[package]
name = "search"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"

[dependencies]
elasticlunr-rs = "2"
ammonia = "3"
lazy_static = "1"
tantivy = "0.12"
isolang = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
num_cpus = "1.12"
chrono = "0.4"

errors = { path = "../errors" }
library = { path = "../library" }
