[package]
name = "content"
version = "0.1.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]

[dependencies]
tera = "0.11.0-beta"
serde = "1.0"
slug = "0.1"
rayon = "0.9"

errors = { path = "../errors" }
config = { path = "../config" }
utils = { path = "../utils" }
rendering = { path = "../rendering" }
front_matter = { path = "../front_matter" }

[dev-dependencies]
tempdir = "0.3"
toml = "0.4"
