title = "My Integration Testing site"
base_url = "https://replace-this-with-your-url.com"
compile_sass = true
generate_feeds = true
theme = "sample"

taxonomies = [
    {name = "categories", feed = true},
    {name = "podcast_authors", feed = true},
]

ignored_content = ["*/ignored.md"]

author = "config@example.com (Config Author)"

[markdown.highlighting]
theme = "custom_gruvbox"
extra_grammars = ["syntaxes/mylang.json"]
extra_themes = ["highlight_themes/custom_gruvbox.json"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
skip_prefixes = [
    "http://[2001:db8::]/",
    "http://invaliddomain",
]

skip_anchor_prefixes = [
    "https://github.com/rust-lang/rust/blob/",
]

[extra.author]
name = "Vincent Prouillet"
