title = "My site"
base_url = "https://replace-this-with-your-url.com"
highlight_code = true
compile_sass = true
generate_rss = true
theme = "sample"
slugify = true

taxonomies = [
    {name = "categories", rss = true},
]

extra_syntaxes = ["syntaxes"]

ignored_content = ["*/ignored.md"]

[link_checker]
skip_prefixes = [
    "http://[2001:db8::]/",
]

skip_anchor_prefixes = [
    "https://github.com/rust-lang/rust/blob/",
]

[extra.author]
name = "Vincent Prouillet"
