base_url = "https://www.getzola.org/"
title = "Zola"
description = "Everything you need to make a static site engine in one binary."

compile_sass = true
build_search_index = true

taxonomies = [
  { name = "theme-tags"}
]

[search]
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "kronuz"
external_links_no_referrer = true
#highlight_theme = "css"
#highlight_themes_css = [
#  { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
#  { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
#]

[link_checker]
internal_level = "warn"

[extra]
author = "Vincent Prouillet"
