base_url = "https://www.getzola.org/"
title = "Zola"
description = "Everything you need to make a static site engine in one binary."

compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "kronuz"


[extra]
author = "Vincent Prouillet"
