base_url = "https://gutenberg.netlify.com/"
title = "Gutenberg"
description = "Everything you need to make a static site engine in one binary. And it's fast"

compile_sass = true
highlight_code = true
insert_anchor_links = true
highlight_theme = "kronuz"

[extra]
author = "Vincent Prouillet"
