base_url = "https://www.getzola.org/"
title = "Zola"
description = "Everything you need to make a static site engine in one binary."

compile_sass = true
build_search_index = true

taxonomies = [
  { name = "theme-tags"}
]

[search]
index_format = "elasticlunr_json"

[markdown]
external_links_class = "external"

[markdown.highlighting]
theme = "catppuccin-mocha"

[link_checker]
internal_level = "warn"

[extra]
author = "Vincent Prouillet"
