[package]
name = "imageproc"
version = "0.1.0"
authors = ["Vojtěch Král <vojtech@kral.hk>"]
edition = "2018"

[dependencies]
lazy_static = "1"
regex = "1.5"
tera = "1"
image = "0.23"
rayon = "1"
webp = "0.1.1"
serde = { version = "1", features = ["derive"] }
svg_metadata = "0.4.1"

errors = { path = "../errors" }
utils = { path = "../utils" }
config = { path = "../config" }

[dev-dependencies]
# TODO: prune
serde_json = "1"
site = { path = "../site" }
